yse_paragraphs_adopter.node_type.*.third_party.yse_paragraphs_adopter:
  type: mapping
  label: 'Promoter per-node type third party settings'
  mapping:
    adopt_embedded_paragraphs:
      type: boolean
      label: 'Adopt embedded paragraphs from WYSIWYG fields on the node'

